-- Commit Chronicles — GitHub ingest. GITHUB_TOKEN secret: docs/snowflake-setup.md step 5.
--
-- Classification uses AI functions where regex can't win alone:
--   * IS_BOT — regex + GitHub's account type resolve the obvious ~99%. Whatever
--     remains (author with no GitHub `type`, no bot marker in name/email) gets sent
--     to AI_CLASSIFY, deduped by (author, email) so we spend one call per distinct
--     ambiguous identity in the batch, not one per commit.
--   * IS_AI_ASSISTED — strict tool-name regex resolves unambiguous mentions. When a
--     candidate token appears (common-English words that are also tool names —
--     cursor, opus, haiku, sonnet, grok — or generic phrases like "generated by"),
--     AI_FILTER decides. No candidate token, no LLM call.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CHRONICLES_WH;
USE SCHEMA CHRONICLES.RAW;

CREATE OR REPLACE NETWORK RULE GITHUB_API_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('api.github.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION GITHUB_API_ACCESS
  ALLOWED_NETWORK_RULES = (GITHUB_API_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (GITHUB_TOKEN)
  ENABLED = TRUE;

-- MAX_COMMITS is clamped to HARD_CAP server-side regardless of what the caller passes.
CREATE OR REPLACE PROCEDURE INGEST_REPO_COMMITS(
  REPO_OWNER STRING,
  REPO_NAME STRING,
  MAX_COMMITS NUMBER DEFAULT 500,
  REF STRING DEFAULT NULL
)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python', 'requests')
HANDLER = 'run'
EXTERNAL_ACCESS_INTEGRATIONS = (GITHUB_API_ACCESS)
SECRETS = ('github_token' = GITHUB_TOKEN)
AS
$$
import re
import requests
from snowflake.snowpark.functions import col

GITHUB_API = "https://api.github.com"
HARD_CAP = 2000
OWNER_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$")
REPO_RE = re.compile(r"^[A-Za-z0-9_.-]{1,100}$")

# GitHub omits author.login when it cannot link a commit to an account, but its own
# noreply addresses still carry the login: "id+login@" (current) or "login@" (legacy).
NOREPLY_RE = re.compile(
    r"(?i)^(?:\d+\+)?([a-z0-9](?:[a-z0-9-]{0,38}))@users\.noreply\.github\.com$"
)


def _login_from_email(email):
    match = NOREPLY_RE.match(email or "")
    return match.group(1) if match else None


def _auth_headers():
    headers = {"Accept": "application/vnd.github+json"}
    import _snowflake
    headers["Authorization"] = f"Bearer {_snowflake.get_generic_secret_string('github_token')}"
    return headers


def run(session, repo_owner, repo_name, max_commits, ref=None):
    if not OWNER_RE.match(repo_owner or "") or not REPO_RE.match(repo_name or "") or ".." in repo_name:
        return {"status": "failed", "errorCode": "invalid_repo_slug"}

    repo_slug = f"{repo_owner}/{repo_name}"
    max_commits = max(1, min(int(max_commits or 500), HARD_CAP))
    headers = _auth_headers()

    repo_resp = requests.get(f"{GITHUB_API}/repos/{repo_slug}", headers=headers, timeout=10)
    if repo_resp.status_code == 404:
        return {"status": "failed", "errorCode": "repo_not_found", "repo": repo_slug}
    repo_resp.raise_for_status()
    if repo_resp.json().get("private"):
        return {"status": "failed", "errorCode": "repo_private", "repo": repo_slug}

    # One over the cap: if it comes back full, the repo is oversized, not truncated.
    fetch_target = max_commits + 1

    rows = []
    page = 1
    per_page = 100
    base_params = {"per_page": per_page}
    if ref:
        base_params["sha"] = ref
    while len(rows) < fetch_target:
        resp = requests.get(
            f"{GITHUB_API}/repos/{repo_slug}/commits",
            headers=headers,
            params={**base_params, "page": page},
            timeout=10,
        )
        if resp.status_code == 409:
            return {"status": "failed", "errorCode": "repo_empty", "repo": repo_slug}
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break
        for c in batch:
            commit = c.get("commit", {}) or {}
            author = commit.get("author", {}) or {}
            committer = commit.get("committer", {}) or {}
            message = commit.get("message", "") or ""
            subject, _, body = message.partition("\n")
            body = body.strip() or None
            gh_author = c.get("author") or {}
            gh_committer = c.get("committer") or {}
            email = (author.get("email") or "").lower() or None
            login = gh_author.get("login") or _login_from_email(email)
            rows.append((
                repo_owner,
                repo_name,
                c.get("sha"),
                author.get("name"),
                login,
                gh_author.get("type"),
                gh_committer.get("type"),
                email,
                subject.strip(),
                body,
                author.get("date"),
                committer.get("date"),
                len(c.get("parents", []) or []),
            ))
            if len(rows) >= fetch_target:
                break
        page += 1

    if not rows:
        return {"status": "failed", "errorCode": "repo_empty", "repo": repo_slug}
    if len(rows) > max_commits:
        return {"status": "failed", "errorCode": "repo_oversized", "repo": repo_slug, "commitCap": max_commits}

    session.table("COMMITS").delete(
        (col("REPO_OWNER") == repo_owner) & (col("REPO_NAME") == repo_name)
    )

    # Stage raw rows so IS_BOT / IS_AI_ASSISTED can be resolved in SQL, where the AI
    # functions live. INGEST_STAGE is declared in schema.sql: an owner's-rights
    # procedure may not create a temporary table. Rows are scoped by repo, so two
    # repos ingesting at once do not see each other.
    session.table("INGEST_STAGE").delete(
        (col("REPO_OWNER") == repo_owner) & (col("REPO_NAME") == repo_name)
    )
    session.create_dataframe(
        rows,
        schema=["REPO_OWNER", "REPO_NAME", "SHA", "AUTHOR", "AUTHOR_LOGIN",
                "GH_AUTHOR_TYPE", "GH_COMMITTER_TYPE", "EMAIL",
                "SUBJECT", "BODY", "AUTHORED_AT", "COMMITTED_AT", "PARENT_COUNT"],
    ).write.mode("append").save_as_table("INGEST_STAGE", column_order="name")

    # Two-stage classification. Cost math:
    #   Bot: |distinct ambiguous authors|, usually 0 in a well-attributed repo.
    #   AI-assisted: |commits whose subject/body contains a candidate token|,
    #   which is a small tail of the batch, not the whole batch.
    session.sql('''
        INSERT INTO COMMITS (
            REPO_OWNER, REPO_NAME, SHA, AUTHOR, AUTHOR_LOGIN, EMAIL,
            SUBJECT, BODY, AUTHORED_AT, COMMITTED_AT, PARENT_COUNT,
            IS_BOT, IS_AI_ASSISTED
        )
        WITH staged AS (
            SELECT * FROM INGEST_STAGE WHERE REPO_OWNER = ? AND REPO_NAME = ?
        ),
        signals AS (
            SELECT
                s.*,
                -- Fast-path bot: GitHub said Bot, or the display name / email
                -- carries a canonical bot marker.
                (   s.GH_AUTHOR_TYPE    = 'Bot'
                 OR s.GH_COMMITTER_TYPE = 'Bot'
                 OR REGEXP_LIKE(COALESCE(s.AUTHOR, ''),
                                '.*([[]bot[]]|dependabot|renovate|github-actions).*', 'i')
                 OR REGEXP_LIKE(COALESCE(s.EMAIL, ''),
                                '.*([[]bot[]]@|noreply@github[.]com).*', 'i')
                ) AS BOT_FROM_SIGNALS,
                -- Ambiguous bot: no fast-path hit AND GitHub could not attribute the
                -- commit to a User account. AI_CLASSIFY decides.
                (   NOT (   s.GH_AUTHOR_TYPE    = 'Bot'
                         OR s.GH_COMMITTER_TYPE = 'Bot'
                         OR REGEXP_LIKE(COALESCE(s.AUTHOR, ''),
                                        '.*([[]bot[]]|dependabot|renovate|github-actions).*', 'i')
                         OR REGEXP_LIKE(COALESCE(s.EMAIL, ''),
                                        '.*([[]bot[]]@|noreply@github[.]com).*', 'i'))
                 AND s.GH_AUTHOR_TYPE IS DISTINCT FROM 'User'
                 AND (s.AUTHOR IS NOT NULL OR s.EMAIL IS NOT NULL)
                ) AS NEEDS_AI_CLASSIFY,
                -- Strict AI-tool regex: unambiguous tool names. TRUE wins outright.
                REGEXP_LIKE(
                    COALESCE(s.SUBJECT, '') || CHR(10) || COALESCE(s.BODY, ''),
                    '.*(claude|anthropic|openai|chatgpt|gpt-[0-9]|copilot|codex|gemini|devin|aider|windsurf|codeium|tabnine|deepseek|llama|mistral).*',
                    'i'
                ) AS AI_STRICT_MATCH,
                -- Candidate AI regex: common-English tool names + generic phrases.
                -- Any hit here goes to AI_FILTER.
                REGEXP_LIKE(
                    COALESCE(s.SUBJECT, '') || CHR(10) || COALESCE(s.BODY, ''),
                    '.*(cursor|opus|haiku|sonnet|grok|generated by|generated with|written by|written with|help of|assistant).*',
                    'i'
                ) AS AI_CANDIDATE_MATCH
            FROM staged s
        ),
        ambiguous_authors AS (
            SELECT DISTINCT
                COALESCE(AUTHOR, '') AS AUTHOR_KEY,
                COALESCE(EMAIL, '')  AS EMAIL_KEY,
                AUTHOR,
                EMAIL
            FROM signals
            WHERE NEEDS_AI_CLASSIFY
        ),
        ai_bot_verdicts AS (
            SELECT
                AUTHOR_KEY,
                EMAIL_KEY,
                (AI_CLASSIFY(
                    'Git author display name: ' || COALESCE(AUTHOR, '(none)') || CHR(10) ||
                    'Git author email: '        || COALESCE(EMAIL,  '(none)'),
                    ['human', 'bot']
                ):labels[0]::STRING = 'bot') AS AI_SAYS_BOT
            FROM ambiguous_authors
        )
        SELECT
            s.REPO_OWNER, s.REPO_NAME, s.SHA, s.AUTHOR, s.AUTHOR_LOGIN, s.EMAIL,
            s.SUBJECT, s.BODY, s.AUTHORED_AT, s.COMMITTED_AT, s.PARENT_COUNT,
            s.BOT_FROM_SIGNALS OR COALESCE(a.AI_SAYS_BOT, FALSE) AS IS_BOT,
            s.AI_STRICT_MATCH
              OR (s.AI_CANDIDATE_MATCH
                  AND AI_FILTER(PROMPT(
                      'Does this commit message credit an AI coding tool for authoring the change? Answer yes or no. Text: {0}',
                      COALESCE(s.SUBJECT, '') || CHR(10) || COALESCE(s.BODY, '')
                  )))
              AS IS_AI_ASSISTED
        FROM signals s
        LEFT JOIN ai_bot_verdicts a
            ON  COALESCE(s.AUTHOR, '') = a.AUTHOR_KEY
            AND COALESCE(s.EMAIL, '')  = a.EMAIL_KEY;
    ''', params=[repo_owner, repo_name]).collect()

    session.table("INGEST_STAGE").delete(
        (col("REPO_OWNER") == repo_owner) & (col("REPO_NAME") == repo_name)
    )

    return {"status": "ready", "repo": repo_slug, "commitCount": len(rows)}
$$;

-- 4. Smoke test once deployed — small, well-known public repo.
-- CALL INGEST_REPO_COMMITS('octocat', 'Hello-World', 50);
