-- Commit Chronicles — warehouse, database, COMMITS table, detector input view.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS CHRONICLES_WH
  WAREHOUSE_SIZE      = 'XSMALL'
  AUTO_SUSPEND        = 60
  AUTO_RESUME         = TRUE
  INITIALLY_SUSPENDED = TRUE
  MAX_CLUSTER_COUNT   = 1
  STATEMENT_TIMEOUT_IN_SECONDS = 300;

USE WAREHOUSE CHRONICLES_WH;

CREATE DATABASE IF NOT EXISTS CHRONICLES;
CREATE SCHEMA IF NOT EXISTS CHRONICLES.RAW;
USE SCHEMA CHRONICLES.RAW;

CREATE TABLE IF NOT EXISTS COMMITS (
  REPO_OWNER     STRING       NOT NULL,
  REPO_NAME      STRING       NOT NULL,
  SHA            STRING       NOT NULL,
  AUTHOR         STRING,
  EMAIL          STRING,
  SUBJECT        STRING,
  BODY           STRING,
  AUTHORED_AT    TIMESTAMP_TZ NOT NULL,   -- normalized to UTC by GitHub; local offset is lost
  COMMITTED_AT   TIMESTAMP_TZ,
  PARENT_COUNT   NUMBER(2,0),             -- >1 = merge
  IS_BOT         BOOLEAN      DEFAULT FALSE,
  IS_AI_ASSISTED BOOLEAN      DEFAULT FALSE
);

-- Hours are UTC, so the nocturne signal skews for non-UTC authors. Fixing it needs
-- author offsets from the Git Data API.
CREATE OR REPLACE VIEW COMMITS_CLEAN AS
SELECT
    REPO_OWNER, REPO_NAME, SHA, AUTHOR, EMAIL, SUBJECT, BODY, AUTHORED_AT, IS_AI_ASSISTED,
    DATE(AUTHORED_AT)    AS AUTHORED_DATE,
    HOUR(AUTHORED_AT)    AS UTC_HOUR,
    DAYNAME(AUTHORED_AT) AS UTC_DOW
FROM COMMITS
WHERE PARENT_COUNT <= 1
  AND NOT IS_BOT
  -- Trailing .* required: Snowflake RLIKE anchors at both ends.
  AND SUBJECT NOT RLIKE '(Merge (pull request|branch|remote)|Bump |chore\\(deps\\)|Update dependenc).*';

